name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Configure Git with GitHub Actions account
        run: |
          git config --global user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"e"

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: npm run deploy

      - name: Clean up
        run: rm -rf build
